version: '2'

services:
  jenkins:
    build: .
    image: jenkins-alpine:2.121.1
    container_name: jenkins-master
    hostname: jenkins-master
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /srv/data/jenkins:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Dmail.smtp.starttls.enable=true -Djava.awt.headless=true"
