version: '2'

services:
  jenkins:
    build: .
    image: jenkins-master-alpine:2.156
    container_name: jenkins-master
    hostname: jenkins-master
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./docker/volume:/var/jenkins_home:rw
    environment:
      - JAVA_OPTS="-Dmail.smtp.starttls.enable=true -Djava.awt.headless=true"
